### ISSUE TITLE
Improve performance of Improve performance of `skorecard.linear.LogisticRegression`

### ISSUE THREAD

**Issue by timvink** [timvink/skorecard#1]
From @WE56SC 

> how to make sure that the sklearn Logistic Regression and the statsmodels logistic regression converge to the same result, cause it is not obvious and it won’t happen by default.

> There is an implementation in skorecard to get an sklearn like logistic regression that would not require statsmodels at all, but I realized that this works well on demosets, and as soon as the data gets to a real size (100k applications), the code runs in memory issues: it can for sure be optimized, but for the moment statsmodels is still the workaround.

# Memory issue
This code can go out of memory easily then the number of rows in X grows. 
```python
        # Initiate matrix of 0's, fill diagonal with each predicted observation's variance
        V = np.diagflat(np.product(predProbs, axis=1))

        # Covariance matrix following the algebra
        self.cov_matrix_ = np.linalg.inv(np.dot(np.dot(X_design.T, V), X_design))

        std_err = np.sqrt(np.diag(self.cov_matrix_)).reshape(1, -1)
```
Indeed, it works great in the demo cases, where `X.shape[0]~10000`, but in projects where `X.shape[0]` increases by at least one order of magnitude, Memory errors might occir

#### Tim's ideas to speed up the current implementation 

- to move as many calculations as possible to a `@property` `.get_stats()` method
- add a parameter to `__init__()` to disable calculating / saving the covariance of coefficients. This is useful when doing grid-searches. 
- In a grid search, when `refit=True`, perhaps we could detect that and enable the computation for the covariance of coefficients only on that fit.

**Comment by guillermo-navas-palencia** [comment]
Hi @timvink,

I think the above can be optimized significantly as follows:

```python
p = np.product(y_pred, axis=1)
self.cov_matrix_ = np.linalg.inv((X * p[..., np.newaxis]).T @ X)
std_err = np.sqrt(np.diag(self.cov_matrix_)).reshape(1, -1)
```

I have tested it with 1e6 records and takes  < 100 ms (i7-6770HQ)

**Comment by timvink** [comment]
Sweet, thanks!

#55 implements your suggestion. The tricks for speeding up `skorecard.linear.LogisticRegression` when used inside a grid search can be addressed later if performance is an issue.
