### ISSUE TITLE
Getting error `name 'make_subplots' is not defined`

### ISSUE THREAD

**Issue by anilkumarpanda** [timvink/skorecard#51]
I get the following error `name 'make_subplots' is not defined` when I try to plot the bucket using the example mentioned in the [docs](https://timvink.github.io/skorecard/tutorials/using-bucketing-process/)

```python
bucketing_process.plot_prebucket("LIMIT_BAL")
```

Python version : 3.7.10

**Comment by timvink** [comment]
Well, you should get a nice error message:

https://github.com/timvink/skorecard/blob/d1987f87e7df66ce8a38e1765de4c76f18974b66/skorecard/reporting/plotting.py#L4-L11

Can you try `from plotly.subplots import make_subplots` ? I suspect that raises an error other than `ModuleNotFoundError`.

**Comment by anilkumarpanda** [comment]
Yes using the import statement works. I think the `plotly` package was not installed.

**Comment by timvink** [comment]
Still strange, because I didn't change the code. Let me know if this pops up again :)
