### ISSUE TITLE
Raise Error for DecisionTreeBuckter when max buckets > levels

### ISSUE THREAD

**Issue by warriordrago** [timvink/skorecard#52]
When you bin categorical variables with DecisionTreeBuckter, an Error can be raised when the number of max_bins is > than number of levels in the categorical variable.

**Comment by sbjelogr** [comment]
You should not use a decision tree bucketer for categoricals

**Comment by warriordrago** [comment]
Then I will ask Dan to adjust the training ;) Closing the issue

**Comment by warriordrago** [comment]
DecisionTreeBuckter should be used for categorical variables
