### ISSUE TITLE
Refactor `bucketing_process._retrieve_special_for_bucketing()`

### ISSUE THREAD

**Issue by timvink** [timvink/skorecard#62]
Instead of using logic on the indexes:

https://github.com/timvink/skorecard/blob/58c179aa69d0df2e3365ddd76ed848af6578e29c/skorecard/pipeline/bucketing_process.py#L285-L310

we could use the naming convention `Special: <label>` to simply lookup the index of the special after prebucketing. That is safer in case we later change how missing values work (f.e. by using negative indexes instead of the last position).

something like:

```python
for column in self._prebucketing_specials.keys():
    prebucket_table = self.prebucket_tables_[column].
    for label in self._prebucketing_specials[column].keys(): 
        indx = prebucket_table[prebucket_table['label'] == f"Special: {label}"]['pre-bucket'].values[0]
        # then update/append self._bucketing_specials[column] 
```

Thoughts @sbjelogr ?

**Comment by sbjelogr** [comment]
This could be an option.

I like the idea of using labels as they are more explicit towards the user (and developers).

But this means that we should update it also in the bucketers (and not only here).

**Comment by sbjelogr** [comment]
If I am not mistaken, now we have also the missing_treatment variable in the constructor of the bucketers, where you can pass the bucket index to assign the missing value to a specific bucket. However, if we move to a label based bucketing, this will probably break.

Any thoughts, @orchardbirds ?

**Comment by orchardbirds** [comment]
Yeah I much prefer the label-based approach, as the `key: [missing_index + 1 + key_ix]  # the key ` is really unclear to me. 

If the current enforcing of missing values breaks, it shouldn't be too hard to fix :)

**Comment by timvink** [comment]
OK, I will pick this up. Thnx for input.

Btw, we don't need to refactor any bucketers, just the `BucketingProcess`.

**Comment by sbjelogr** [comment]
Well, let's keep the bucketers API consistent with the bucketing process API, otherwise the API begins to diverge.
