### ISSUE TITLE
distance in Agglomerative Bucketing

### ISSUE THREAD

**Issue by orchardbirds** [timvink/skorecard#77]
From the [latest version of sklearn](https://scikit-learn.org/stable/whats_new/v0.24.html#sklearn-cluster)

"[...]a new parameter compute_distances. When set to True, distances between clusters are computed and stored in the distances_ attribute even when the parameter distance_threshold is not used. This new parameter is useful to produce dendrogram visualizations, but introduces a computational and memory overhead. #17984 by Michael Riedmann, Emilie Delattre, and Francesco Casalegno"

Would it be useful to enable this, or is this overkill?

**Comment by timvink** [comment]
Best thing is to enable the users to pass this, and to access the fitted models. Then we don't have to explicitly accomodate this use-case but leave the flexibility to the user.
