### ISSUE TITLE
Does UserInputBucketer need a fit method?

### ISSUE THREAD

**Issue by sbjelogr** [timvink/skorecard#91]
There is no logical need with the UserInputBucketer would need a fit method.

Currently it's implemented only to provide the bucket_table and the plot.

However, those could also be generated in the constructor.

Any thoughts on this, @timvink ?

**Comment by timvink** [comment]
Well you need X to calculate the bucket table. In the init, there's self.features_bucket_mapping_ , indicating the class is already fitted on init (sklearn convention). 

I would leave it as is, but update the docstring of .fit() to better reflect why it's there & that calling it is not necessary if you don't want tables/plots
